# 应用服务 WEB 访问端口
server:
  port: 9998

# 应用名称
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: springboot-demo
  profiles:
    active: dev


mybatis:
  config-location: classpath:mapper/*.xml

logging:
  level:
    com.yunjia.ding.mapper: debug
